todolist/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from user.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/$', index, name="index"),
    url(r'^user/', include('user.urls', namespace="user", app_name='user')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    #
    # urlpatterns = [
    #                   url(r'^__debug__/', include(debug_toolbar.urls)),
    #               ] + urlpatterns

user/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from .views import Login, logout_action, ProfileView, Register, PasswordChange, PasswordReset

admin.autodiscover()

urlpatterns = [
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^register/$', Register.as_view(), name='register'),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', logout_action, name='logout'),
    url(r'^password_change/$', PasswordChange.as_view(), name='password_change'),
    url(r'^password_reset/request/$', PasswordReset.Request.as_view(), name='password_reset_request'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordReset.Form.as_view(), name='password_reset_form'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-Hant-TW">
<head>
    <meta charset="utf-8">
    <meta lang="zh-Hant-TW">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/basic.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <style>
        * {
            font-family: Microsoft JhengHei, Heiti TC, WenQuanYi Zen Hei, LiHei Pro, DFKai-sb, monospace;
        }
    </style>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
<nav class="navbar navbar-default bg-primary navbar-fixed-top" role="navigation">
    <div class="container">
        <div style="margin-left: 40px" class="navbar-header col-sm-3 col-md-3">
            <a class="navbar-brand" href={% url 'index' %}><strong>首頁</strong></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse col-sm-9 col-md-9 pull-right">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% block feature %}{% endblock %}
                </li>
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'user:profile' %}" class="navbar-link"><b>{{ request.user.username }}</b></a>
                    </li>
                    <li>
                        <a href="{% url 'user:logout' %}" class="navbar-link"><b>登出</b></a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'user:login' %}?next={{ request.path }}" class="navbar-link"><b>登入</b></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div align="center" class="container" style="margin-top: 30px">
    {% block header %}{% endblock %}
    {% block main %}{% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    首頁 Main Page
{% endblock %}
{% block header %}
    <p align="center" class="h2">
        首頁 Main Page
    </p><br>
{% endblock %}
{% block main %}
    <table border="0">
        <tr>
            <td align="right">待辦事項：</td>
            <td><a href="{% url "todolist:index" %}">ToDoList</a></td>
        </tr>
        <tr>
            <td align="right">使用者資料：</td>
            <td><a href="{% url "user:profile" %}">個人資料</a></td>
        </tr>
        <tr>
            <td align="right">作者簡介：</td>
            <td><a href="{% url "self_introduction:index" %}">關於作者</a></td>
        </tr>
    </table>
{% endblock %}