todolist/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from user.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^/$', index, name="index"),
    url(r'^user/', include('user.urls', namespace="user", app_name='user')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # import debug_toolbar
    #
    # urlpatterns = [
    #                   url(r'^__debug__/', include(debug_toolbar.urls)),
    #               ] + urlpatterns

user/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, \
    password_reset_complete
from .views import Login, logout_action, ProfileView, Register, PasswordChange, PasswordReset

admin.autodiscover()

urlpatterns = [
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^register/$', Register.as_view(), name='register'),
    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', logout_action, name='logout'),
    url(r'^password_change/$', PasswordChange.as_view(), name='password_change'),
    url(r'^password_reset/request/$', PasswordReset.Request.as_view(), name='password_reset_request'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        PasswordReset.Form.as_view(), name='password_reset_form'),
]

user/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, unique=True)

user/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
# todo login required class-based view
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.conf import settings
from .form import UserForm, UserCreateForm, PasswordResetRequestForm, UserPasswordResetForm, UserPasswordChangeForm
from .models import Profile
import json

UserModel = get_user_model()


class HttpBase(object):
    http_method_names = ['get', 'post']

    @staticmethod
    def redirect(request, target):
        return HttpResponseRedirect(request.GET['next']) if "next" in request.GET else redirect(target)


class Login(View, HttpBase):
    # todo 輸入信箱 寄送認證信
    context = {"header": "登入 Login"}

    def __init__(self):
        self.context = {}
        super(Login, self).__init__()

    def dispatch(self, *args, **kwargs):
        return super(self.__class__, self).dispatch(*args, **kwargs)

    def get(self, request):
        if request.user.is_authenticated:
            return self.redirect(request=request, target=reverse("index"))
        else:
            return self._common_task(request)

    def post(self, request):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return self.redirect(request=request, target=reverse('index'))
        else:
            self.context["error_message"] = "帳號或密碼錯誤，請重新輸入"
            return self._common_task(request)

    def _common_task(self, request):
        return render(request, "user/login.html", self.context)


def logout_action(request):
    logout(request)
    return redirect(reverse('index'))


class Register(View, HttpBase):
    def __init__(self):
        self.context = {}
        super(Register, self).__init__()

    def dispatch(self, *args, **kwargs):
        return super(self.__class__, self).dispatch(*args, **kwargs)

    def get(self, request):
        if request.user.is_authenticated:
            return self.redirect(request=request, target=reverse("user:profile"))
        self.context["form"] = UserCreateForm()
        return self._common_task(request)

    def post(self, request):
        form = UserCreateForm(request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            return redirect(reverse('user:login'))
        error_message = ""
        errors = json.loads(form.errors.as_json())
        for error in errors:
            for tmp in errors[error]:
                error_message += tmp['message'] + "\n"
        self.context["form"] = form
        self.context["error_message"] = error_message
        return self._common_task(request)

    def _common_task(self, request):
        return render(request, 'user/register.html', self.context)


class ProfileView(LoginRequiredMixin, View, HttpBase):
    login_url = "/user/login"

    def __init__(self):
        self.context = {}
        super(ProfileView, self).__init__()

    def get(self, request):
        user = User.objects.get(id=request.user.id)
        self.context['form'] = UserForm(instance=user)
        return self._common_task(request=request)

    def post(self, request):
        user = User.objects.get(id=request.user.id)
        form = UserForm(request.POST, instance=user)
        print(form.data)
        if form.is_valid():
            if user.check_password(form.cleaned_data['password']):
                form.save()
            else:
                self.context["error_message"] = "密碼錯誤！請再次確認"
        else:
            error_message = ""
            errors = json.loads(form.errors.as_json())
            print(errors)
            for error in errors:
                for tmp in errors[error]:
                    error_message += tmp['message'] + "\n"
            self.context["error_message"] = error_message
        return self.get(request)

    def _common_task(self, request):
        return render(request, 'user/profile.html', self.context)


class PasswordChange(LoginRequiredMixin, View, HttpBase):
    def __init__(self):
        self.context = {}
        super(PasswordChange, self).__init__()

    def get(self, request):
        self.context['form'] = UserPasswordChangeForm
        return render(request, "user/password_change_form.html", self.context)

    def post(self, request):
        user = User.objects.get(id=request.user.id)
        print(request.POST)
        form = UserPasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            logout(request)
            return render(request, 'user/password_change_done.html', self.context)
        else:
            error_message = ""
            errors = json.loads(form.errors.as_json())
            print(errors)
            for error in errors:
                for tmp in errors[error]:
                    error_message += tmp['message'] + "\n"
            self.context["error_message"] = error_message
        return self.get(request)


class PasswordReset(object):
    class Request(View, HttpBase):

        def __init__(self):
            self.context = {}
            super(View, self).__init__()

        def get(self, request):
            if request.user.is_authenticated:
                return self.redirect(request=request, target=reverse("index"))
            else:
                return render(request, "user/password_reset_request.html", self.context)

        def post(self, request):
            form = PasswordResetRequestForm(request.POST)
            if form.is_valid():
                # todo password reset form 可在 form.py 繼承django預設並對其進行客製(email內容等等)
                form.save(request=request, email_template_name="user/password_reset_email.html",
                          use_https=request.is_secure(), domain_override=settings.HOST)
                '''
                from django.contrib.sites.shortcuts import get_current_site
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
                site_name = domain = domain_override
                from django.contrib.auth.tokens import default_token_generator
                token= default_token_generator.make_token(user),
                protocol='https' if request.is_secure() else 'http',
                '''
                # todo: special: need to pass some parameters to method
                return render(request, "user/password_reset_send_email.html", self.context)
            else:
                error_message = ""
                errors = json.loads(form.errors.as_json())
                print(errors)
                for error in errors:
                    for tmp in errors[error]:
                        error_message += tmp['message'] + "\n"
                return render(request, "user/password_reset_request.html", self.context)

    class Form(View, HttpBase):

        def __init__(self):
            self.context = {}
            super(View, self).__init__()

        def __check_idenity(self, uidb64=None, token=None):
            if uidb64 is not None and token is not None:
                uid = force_text(urlsafe_base64_decode(uidb64))
                user = UserModel._default_manager.get(pk=uid)
                if user is not None and default_token_generator.check_token(user, token):
                    self.context['validlink'] = True
                    return user
            return None

        def get(self, request, uidb64=None, token=None):
            if request.user.is_authenticated:
                return self.redirect(request=request, target=reverse("index"))
            else:
                user = self.__check_idenity(uidb64=uidb64, token=token)
                if user is None:
                    return redirect(reverse("index"))
                # form = UserPasswordResetForm(user)
                return render(request, "user/password_reset_form.html", self.context)

        def post(self, request, uidb64=None, token=None):
            if request.user.is_authenticated:
                return self.redirect(request=request, target=reverse("index"))
            else:
                user = self.__check_idenity(uidb64=uidb64, token=token)
                if user is not None:
                    form = UserPasswordResetForm(user, request.POST)
                    if form.is_valid():
                        form.save()
                        return redirect(reverse("user:profile"))
                    return self.get(request=request, uidb64=uidb64, token=token)
                else:
                    return redirect(reverse("index"))


def index(request):
    return render(request, 'index.html', locals())

templates/user/base.html
{% extends 'base.html' %}
{% load static %}

templates/user/login.html
{% extends 'user/base.html' %}
{% block title %}
    登入
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        登入 LOGIN
    </p><br>
{% endblock %}
{% block main %}
    {% if error_message %}
        <p><font color="red">{{ error_message }}</font></p>
    {% endif %}
    <form method="post" action="{% url 'user:login' %}">{% csrf_token %}
        <table align="center">
            <tr>
                <td align="right"><p><label for="id_username">使用者名稱：</label></p></td>
                <td><p><input type="text" name="username" autofocus maxlength="254" required id="id_username"/></p></td>
            </tr>
            <tr>
                <td align="right"><p><label for="id_password">密碼：</label></p></td>
                <td><p><input type="password" name="password" required id="id_password"/></p></td>
            </tr>
        </table>
        <button type="submit" name="login">登入</button>
    </form>
    <p>
        <label style="margin: 10px 5px 10px 10px"><a href="{% url 'user:password_reset_request' %}">忘記密碼?</a></label>
        <label style="margin: 10px 10px 10px 5px"><a href="{% url 'user:register' %}">馬上註冊!</a></label>
    </p>
{% endblock %}

templates/user/password_change_done.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
    更改密碼成功 Change Password Success
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        更改密碼成功 Change Password Success
    </p><br>
{% endblock %}
{% block main %}
    <p>
        恭喜您已順利更改密碼，請使用新密碼重新登入
    </p>
    <a href="{% url "user:login" %}">將在5秒後重新導向登入頁面......如未導向請點擊此處</a>
    <meta http-equiv="refresh" content="5;url={% url "user:login" %}">
{% endblock %}

templates/user/password_change_form.html
{% extends "user/base.html" %}
{% load static %}
{% block title %}
    更改密碼 Change Password
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        更改密碼 Change Password
    </p><br>
{% endblock %}
{% block main %}
    {% if error_message %}
        <p><font color="red">{{ error_message|linebreaksbr }}</font></p>
    {% endif %}
    <form method="post" action="{% url "user:password_change" %}">{% csrf_token %}
        <table border="0">
            <tr>
                <td align="right">
                    <p>
                        <label for="id_old_password">舊密碼：</label>
                    </p>
                </td>
                <td>
                    <p>
                        <input type="password" name="old_password" autofocus required id="id_old_password"/>
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <p>
                        <label for="id_new_password1">新密碼：</label>
                    </p>
                </td>
                <td>
                    <p>
                        <input type="password" name="new_password1" required id="id_new_password1"/>
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <p>
                        <label for="id_new_password2">新密碼確認：</label>
                    </p>
                </td>
                <td>
                    <p>
                        <input type="password" name="new_password2" required id="id_new_password2"/>
                    </p>
                </td>
            </tr>
        </table>
        <button type="submit" name="change_password" value="" class="btn btn-success">變更密碼</button>
    </form>
{% endblock %}

templates/user/password_reset_complete.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
    更改密碼成功 Change Password Success
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        更改密碼成功 Change Password Success
    </p><br>
{% endblock %}
{% block main %}
    <p>
        恭喜您已順利更改密碼，請使用新密碼重新登入
    </p>
    <a href="{% url "user:login" %}">將在5秒後重新導向登入頁面......如未導向請點擊此處</a>
    <meta http-equiv="refresh" content="5;url={% url "user:login" %}">
{% endblock %}

templates/user/password_reset_done.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
    密碼重置信已送出 Password Reset Email Sent
{% endblock %}
{% block header %}
    密碼重置信已送出 Password Reset Email Sent
{% endblock %}
{% block main %}
    <p>密碼重置信已送出，請至您輸入的信箱收取</p>
{% endblock %}

templates/user/password_reset_email.html
{% autoescape off %}
    {{ user.username }} 您好：

    感謝您對 {{ domain }} 的支持與使用，我們接收到您重新設置密碼的要求，很高興為您提供服務！

    請到下列頁面設定新密碼：
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'user:password_reset_form' uidb64=uid token=token %}
    {% endblock %}
    如果沒有您並沒有此要求請忽略此封信件，感謝您。

    感謝使用本網站！

    {{ site_name }} 團隊感謝您的使用！

{% endautoescape %}

templates/user/password_reset_form.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
    更改密碼 Change Password
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        更改密碼 Change Password
    </p><br>
{% endblock %}
{% block main %}
    {% if validlink %}
        <p>
            請輸入新密碼<br/>
        </p>
        <form action="" method="post">{% csrf_token %}
            <table>
                <tr>
                    {#                    <td>{{ form.new_password1.errors }}#}
                    <td><label for="id_new_password1">新密碼：</label></td>
                    <td><input type="password" name="new_password1" id="id_new_password1"></td>
                    {#                    <td>{{ form.new_password1 }}</td>#}
                </tr>
                <tr>
                    {#                    <td>{{ form.new_password2.errors }}#}
                    <td><label for="id_new_password2">確認密碼：</label></td>
                    <td><input type="password" name="new_password2" id="id_new_password2"></td>
                    {#                    <td>{{ form.new_password2 }}</td>#}
                </tr>
            </table>
            <button name="submit" value="">送出</button>
        </form>
    {% else %}
        <h1 style="color: red">無存取權限</h1>
        <p>請再次確認連結正確與否，或請洽技術人員</p>
    {% endif %}
{% endblock %}

templates/user/password_reset_request.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
    忘記密碼 Forget Password
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        忘記密碼 Forget Password
    </p><br>
{% endblock %}
{% block main %}
    <p>請輸入您註冊時所輸入的個人信箱</p>
    {% if error_message %}
        <p><font color="red">{{ error_message|linebreaksbr }}</font></p>
    {% endif %}
    <form action="{% url "user:password_reset_request" %}" method="post">{% csrf_token %}
        <table border="0">
            <tr>
                <td><label for="id_email">信箱：</label></td>
                <td><input name="email" id="id_email" type="email"></td>
            </tr>
        </table>
    <button type="submit" name="submit" value="">送出</button>
    </form>
{% endblock %}

templates/user/password_reset_send_email.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
    密碼重置信已送出 Password Reset Email Sent
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
    密碼重置信已送出 Password Reset Email Sent
    </p><br>
{% endblock %}
{% block main %}
    <p>密碼重置信已送出，請至您輸入的信箱收取</p>
{% endblock %}

templates/user/profile.html
{% extends 'user/base.html' %}
{% block title %}
    個人資料 Profile
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        個人資料 Profile
    </p><br>
{% endblock %}
{% block main %}
    {% if error_message %}
        <p><font color="red">{{ error_message|linebreaksbr }}</font></p>
    {% endif %}
    <form action="{% url "user:profile" %}" method="post" autocomplete="off">{% csrf_token %}
        <table align="center">
            <tr style="font-weight: bold">
                <td align="right"><p>帳號：</p></td>
                <td>
                    <p>
                        {{ request.user.username }}
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right"><p><label for="id_first_name">姓氏：</label></p></td>
                <td>
                    <p>
                        <input type="text" name="first_name" id="id_first_name"/>
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right"><p><label for="id_last_name">姓名：</label></p></td>
                <td>
                    <p>
                        <input type="text" name="last_name" id="id_last_name"/>
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right"><p><label for="id_email">信箱：</label></p></td>
                <td>
                    <p>
                        <input type="email" name="email" id="id_email" autocomplete="off"
                               value="{% if form.email %}{{ form.email.value }}{% endif %}"/>
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right">
                    <p>
                        <label for="id_password">確認密碼：</label>
                    </p>
                </td>
                <td>
                    <p>
                        <input type="password" name="password" required id="id_password" autocomplete="off" value=""/>
                    </p>
                </td>
            </tr>
        </table>
        <p>
            <button name="submit" value="profile_change">送出</button>
        </p>
    </form>
    <p>
        <label style="margin: 10px 5px 10px 10px"><a href="{% url 'user:password_change' %}">更改密碼</a></label>
    </p>
{% endblock %}

templates/user/register.html
{% extends 'user/base.html' %}
{% block title %}
    註冊 Register
{% endblock %}
{% block header %}
    <p align="center" class="h2 text-uppercase">
        註冊 register
    </p><br>
{% endblock %}
{% block main %}
    {% if error_message %}
        <p><font color="red">{{ error_message|linebreaksbr }}</font></p>
    {% endif %}
    <form action="" method="post">{% csrf_token %}
        <table align="center">
            <tr>
                <td align="right"><p><label for="id_username">使用者名稱：</label></p></td>
                <td><p>
                    <input type="text" name="username" maxlength="150" autofocus required id="id_username"
                           value="{% if form.username.value %}{{ form.username.value }}{% endif %}"/>
                </p></td>
            </tr>
            <tr>
                <td align="right"><p><label for="id_password1">建立密碼：</label></p></td>
                <td>
                    <p>
                        <input type="password" name="password1" required id="id_password1"/>
                    </p>
                </td>
            </tr>
            <tr>
                <td align="right"><p><label for="id_password2">密碼確認：</label></p></td>
                <td>
                    <p>
                        <input type="password" name="password2" required id="id_password2"/>
                    </p>
                </td>
            </tr>
        </table>
        <button type="submit" name="register" value="">送出</button>
    </form>
{% endblock %}